export enum PermissionKeys {
    MANAGE_USER = 'MANAGE_USER',
    APPROVE_ADVERTISEMENT = 'APPROVE_ADVERTISEMENT',
    VIEW_OWN_PROFILE = 'VIEW_OWN_PROFILE',
    APPROVE_COMPANY = 'APPROVE_COMPANY',
    APPROVE_CONSULTANT = 'APPROVE_CONSULTANT',
    VIEW_ADVERTISEMENT = 'VIEW_ADVERTISEMENT',
    CREATE_ADVERTISEMENT = 'CREATE_ADVERTISEMENT',
    CREATE_COMPANY = 'CREATE_COMPANY',
    UPDATE_ADVERTISEMENT = 'UPDATE_ADVERTISEMENT',
    CREATE_CONSULTANT_PROFILE = 'CREATE_CONSULTANT_PROFILE',
    DELETE_ADVERTISEMENT = 'DELETE_ADVERTISEMENT',
    UPDATE_COMPANY_PROFILE = 'UPDATE_COMPANY_PROFILE',
    UPDATE_CONSULTANT_PROFILE = 'UPDATE_CONSULTANT_PROFILE',
    UPDATE_OWN_PROFILE = 'UPDATE_OWN_PROFILE',
    GET_PING = 'GET_PING'
}
